
import { Formatter } from '../helpers/formatter.js';

const styles = {
  h1: {
    fontSize: 20,
    bold: true,
    margin: [0, 5],
  },
  h2: {
    fontSize: 16,
    bold: true,
  },
  h3: {
    fontSize: 14,
    bold: true,
  },
};

export const billReport = (data) => {
  const billProducts = data.products;
  const logoBase64 = data.logoBase64;

  const subTotal = billProducts.reduce(
    (acc, product) => acc + product.Total,
    0,
  );

  const granTotal = subTotal * 1.16;

  const content = [];

  // Add logo if Base64 is provided
  if (logoBase64) {
    content.push({
      image: logoBase64,
      width: 120,
    });

    // Add a separation line after the logo
    content.push({
      canvas: [
        {
          type: 'line',
          x1: 0,
          y1: 5,
          x2: 515,
          y2: 5,
          lineWidth: 1,
        },
      ],
    });
  }

  content.push(
    {
      text: `${data.nombre_empresa}`,
      style: 'h1',
    },
    {
      columns: [
        {
          text: [
            `${new Date().toLocaleString()}`,
          ],
          alignment: 'right',
        },
      ],
    },
    {
      text: [
        {
          text: 'Cotizando a: ',
          style: 'h2',
        },
        `${data.clientPhone}\n`,
      ],
    },
    {
      margin: [0, 20],
      layout: 'lightHorizontalLines',
      table: {
        widths: [50, '*', 'auto', 'auto', 'auto'],
        headerRows: 1,
        body: [
          [
            { text: 'ID', alignment: 'center' },
            'Producto',
            'Precio',
            'Cantidad',
            'Total',
          ],
          ...billProducts.map((product) => [
            { text: product.ID, alignment: 'center' },
            product.Producto,
            Formatter.currency(product.Precio),
            product.Cantidad,
            {
              text: Formatter.currency(product.Total),
              bold: true,
              alignment: 'right',
            },
          ]),
          [{}, {}, {}, {}, {}],
          [
            { text: 'Subtotal', colSpan: 4, alignment: 'right' },
            {},
            {},
            {},
            {
              text: Formatter.currency(subTotal),
              bold: true,
              alignment: 'right',
            },
          ],
          [
            { text: 'IVA 16%', colSpan: 4, alignment: 'right' },
            {},
            {},
            {},
            {
              text: Formatter.currency(subTotal * 0.16),
              bold: true,
              alignment: 'right',
            },
          ],
          [
            {},
            {},
            {
              text: 'Gran Total',
              colSpan: 2,
              alignment: 'right',
              fillColor: 'black',
              color: 'white',
              bold: true,
              margin: [5, 5],
              fontSize: 14,
            },
            {},
            {
              text: Formatter.currency(granTotal),
              bold: true,
              alignment: 'right',
              fillColor: 'black',
              color: 'white',
              margin: [5, 5],
              fontSize: 14,
            },
          ],
        ],
      },
    }
  );

  return {
    defaultStyle: {
      // fontSize: 8,
    },
    pageSize: 'A4',
    header: {
      text: 'Factura',
      alignment: 'right',
      margin: [10, 10],
    },
    footer: {
      text: 'Generated by POINTSALES',
      alignment: 'right',
      margin: [10, 10],
    },
    content: content,
    styles: styles,
  };
};